# Numpy

### Creating arrays

In [1]:
import numpy as np

In [2]:
# Creating numpy array
a = np.array([0, 1, 2])

In [3]:
# Checking data type of elements in numpy array
a.dtype

dtype('int32')

In [4]:
# Changing data type of elements
a = np.array([1, 2, 3], dtype='float32')
a.dtype

dtype('float32')

In [5]:
# Changing data type of elements second method
a.astype('float32')

array([1., 2., 3.], dtype=float32)

In [6]:
# Creating two dimensional array
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [7]:
# Checking shape of array
a.shape

(2, 3)

In [8]:
# Declaring array for reshaping
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
a.shape

(16,)

In [9]:
# First method
a = a.reshape(4, 4)
a.shape

(4, 4)

In [10]:
# second method
a.shape = (2, 2, 4)
a.shape

(2, 2, 4)

In [11]:
# creating an array of zeros
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# creating an empty array
empty = np.empty((3, 3))
empty.dtype

dtype('float64')

In [13]:
# creating an array of ones with optional dtype
ones = np.ones((3, 3), dtype='float32')
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# Creating random array of floating numbers in range of (0, 1)
randoms = np.random.rand(3, 3)
print(randoms)

[[0.49412153 0.00288747 0.66711701]
 [0.31993714 0.39373354 0.94024048]
 [0.52226877 0.32107423 0.01720738]]


In [15]:
# Creating same shape arrays
x = np.random.rand(2, 3)
y = np.random.rand(3, 4)
z = np.random.rand(4, 2)

In [16]:
print(np.zeros_like(x))

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Their actual value is meaningless
print(np.empty_like(y))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
print(np.ones_like(z))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## Accessing Arrays

In [19]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

print(A[0])
[a for a in A]

0


[0, 1, 2, 3, 4, 5, 6, 7, 8]

### Indexing and slicing

In [20]:
B = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

# element at index 0
B[0]

array([0, 1, 2])

In [21]:
# element at index [0, 1]
print(B[0, 1])
print(B[(0, 1)])

1
1


In [22]:
# slicing on the first dimension
B[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
# slicing on two dimensions
B[0:2, 0:2]

array([[0, 1],
       [3, 4]])

In [24]:
# updating value using index
B[0, 1] = 8
B

array([[0, 8, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
# updating value using slice
B[0:2, 0:2] = [[1, 1], [1, 1]]
B

array([[1, 1, 2],
       [1, 1, 5],
       [6, 7, 8]])

In [26]:
# Creating a view of array. Note that it's not a copy of array
C = np.array([1, 1, 1, 1])
c_view = C[0:2]
print(c_view)
c_view[0] = 2
print(C)

[1 1]
[2 1 1 1]


In [27]:
# An array with 10 elements of size 2 will be:
r_i = np.random.rand(10, 2)
print(r_i)

[[0.0898616  0.93680472]
 [0.5807086  0.71806211]
 [0.82022797 0.75201984]
 [0.22245878 0.25201427]
 [0.513661   0.76044239]
 [0.41942885 0.60135113]
 [0.27264952 0.83496068]
 [0.40684013 0.53627806]
 [0.97267008 0.42518922]
 [0.03370689 0.08173266]]


In [28]:
# getting x component of each coordinate
x_i = r_i[:, 0]
print(x_i)

[0.0898616  0.5807086  0.82022797 0.22245878 0.513661   0.41942885
 0.27264952 0.40684013 0.97267008 0.03370689]


In [29]:
# getting all components of first row
y_i = r_i[0, :]
print(y_i)
# or
print(r_i[0])

[0.0898616  0.93680472]
[0.0898616  0.93680472]


### Fance indexing

In [30]:
# index an array using another Numpy array
d = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
idx = np.array([0, 2, 3])
d[idx]

array([9, 7, 6])

In [31]:
# fancy indexing on multiple dimensions
e = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
idx1 = np.array([0, 1])
idx2 = np.array([2, 2])
# e[select rows 0 and 1, select cols 2 and 2]
e[idx1, idx2]

array([2, 5])

In [32]:
# using normal lists
print(e[np.array([0, 1])])
# or
print(e[[0, 1]])

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [33]:
# using tuple
print(e[(0, 1)])
# or
print(e[0, 1])

1
1


In [34]:
# using multi-dimension index arrays
idx1 = [[0, 1], [3, 2]]
idx2 = [[0, 2], [1, 1]]
e[idx1, idx2]

array([[ 0,  5],
       [10,  7]])

In [35]:
# combining slicing and fancy indexing to swap x and y
r_i = np.random.rand(10, 2)
print(r_i)
r_i[:, [0, 1]] = r_i[:, [1, 0]]
print(r_i)

[[0.0896479  0.95319381]
 [0.13620333 0.40041118]
 [0.9706028  0.32565235]
 [0.31145983 0.26285624]
 [0.88517023 0.17393999]
 [0.73648261 0.99510914]
 [0.34494435 0.39120714]
 [0.4317799  0.49474416]
 [0.45029586 0.59175214]
 [0.122078   0.54510951]]
[[0.95319381 0.0896479 ]
 [0.40041118 0.13620333]
 [0.32565235 0.9706028 ]
 [0.26285624 0.31145983]
 [0.17393999 0.88517023]
 [0.99510914 0.73648261]
 [0.39120714 0.34494435]
 [0.49474416 0.4317799 ]
 [0.59175214 0.45029586]
 [0.54510951 0.122078  ]]


In [36]:
# using a bool type index array. every element corresponding to true will be extracted. this is called mask
f = np.array([0, 1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, False, False])
f[mask]

array([0, 2])

In [37]:
# getting more performance using np.take
r_i = np.random.rand(100, 2)
idx = np.arange(50)

In [38]:
%timeit r_i[idx]

2.49 µs ± 91.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [39]:
%timeit np.take(r_i, idx, axis=0)

3.5 µs ± 477 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
# Here np.take shows less performance than normal which is against the performance mentioned in the book.

In [41]:
# when index array is of boolean type we will use numpy.compress 
idx = np.ones(100, dtype='bool')

In [42]:
%timeit r_i[idx]

3.42 µs ± 96.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [43]:
%timeit np.compress(idx, r_i, axis=0)

3.24 µs ± 48 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [44]:
# np.compress is giving a slight speed improvement.

## Broadcasting

#### Broadcasting is a clever set of rules that enables fast array calculations for arrays of similar (but not equal!) shapes.

In [47]:
# Multiplying two same shape arrays
G = np.array([[1, 2], [3, 4]])
H = np.array([[5, 6], [7, 8]])

G * H

array([[ 5, 12],
       [21, 32]])

In [48]:
# Multiplying an array with a scalar
G * 2

array([[2, 4],
       [6, 8]])

In [50]:
# Multiplying two different shape arrays
I = np.random.rand(5, 10, 2)
J = np.random.rand(5, 2)

# Creating a new axis to match shapes of both arrays
I * J[:, np.newaxis, :]

array([[[0.19888064, 0.21437696],
        [0.5130943 , 0.10874355],
        [0.25653249, 0.09925454],
        [0.57590539, 0.14364903],
        [0.70029   , 0.21650444],
        [0.54336981, 0.18945962],
        [0.00224535, 0.32305838],
        [0.6984232 , 0.08711782],
        [0.34523884, 0.06485625],
        [0.50808012, 0.24337692]],

       [[0.71321386, 0.1481079 ],
        [0.81233409, 0.02784064],
        [0.39472338, 0.04159583],
        [0.48576094, 0.07944065],
        [0.54755988, 0.08314988],
        [0.5411728 , 0.0810703 ],
        [0.20821487, 0.08974472],
        [0.14969847, 0.04550741],
        [0.38991038, 0.07776686],
        [0.63292181, 0.11774307]],

       [[0.13446244, 0.07416001],
        [0.21751164, 0.02064226],
        [0.06537455, 0.00933933],
        [0.27314061, 0.11076376],
        [0.28556143, 0.08924037],
        [0.11411862, 0.06937409],
        [0.18170581, 0.06396811],
        [0.05567885, 0.07797929],
        [0.0028258 , 0.10730186],
        [0

In [51]:
# Outer Product: The outer product is a matrix containing the product of all the possible combinations (i, j) 
# of the two array elements.

K = np.array([3, 2, 1])
L = np.array([4, 5, 6])

# The outer product can be calculated as follow
KL = K[:, np.newaxis] * L[np.newaxis, :]

In [52]:
print(KL)

[[12 15 18]
 [ 8 10 12]
 [ 4  5  6]]
