# Numpy

### Creating arrays

In [1]:
import numpy as np

In [2]:
# Creating numpy array
a = np.array([0, 1, 2])

In [3]:
# Checking data type of elements in numpy array
a.dtype

dtype('int32')

In [4]:
# Changing data type of elements
a = np.array([1, 2, 3], dtype='float32')
a.dtype

dtype('float32')

In [5]:
# Changing data type of elements second method
a.astype('float32')

array([1., 2., 3.], dtype=float32)

In [6]:
# Creating two dimensional array
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [7]:
# Checking shape of array
a.shape

(2, 3)

In [8]:
# Declaring array for reshaping
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
a.shape

(16,)

In [9]:
# First method
a = a.reshape(4, 4)
a.shape

(4, 4)

In [10]:
# second method
a.shape = (2, 2, 4)
a.shape

(2, 2, 4)

In [11]:
# creating an array of zeros
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# creating an empty array
empty = np.empty((3, 3))
empty.dtype

dtype('float64')

In [13]:
# creating an array of ones with optional dtype
ones = np.ones((3, 3), dtype='float32')
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# Creating random array of floating numbers in range of (0, 1)
randoms = np.random.rand(3, 3)
print(randoms)

[[0.00633303 0.32572321 0.02394083]
 [0.23227763 0.15901731 0.48335349]
 [0.95446592 0.57515856 0.45763244]]


In [15]:
# Creating same shape arrays
x = np.random.rand(2, 3)
y = np.random.rand(3, 4)
z = np.random.rand(4, 2)

In [16]:
print(np.zeros_like(x))

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Their actual value is meaningless
print(np.empty_like(y))

[[9.73248346e-312 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.11260619e-306 1.04082753e-047 4.97645901e-091 1.27964675e+161]
 [3.61392451e+174 2.67901217e+184 3.99910963e+252 1.46030983e-319]]


In [18]:
print(np.ones_like(z))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## Accessing Arrays

In [19]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

print(A[0])
[a for a in A]

0


[0, 1, 2, 3, 4, 5, 6, 7, 8]

### Indexing and slicing

In [20]:
B = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

# element at index 0
B[0]

array([0, 1, 2])

In [21]:
# element at index [0, 1]
print(B[0, 1])
print(B[(0, 1)])

1
1


In [22]:
# slicing on the first dimension
B[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
# slicing on two dimensions
B[0:2, 0:2]

array([[0, 1],
       [3, 4]])

In [24]:
# updating value using index
B[0, 1] = 8
B

array([[0, 8, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
# updating value using slice
B[0:2, 0:2] = [[1, 1], [1, 1]]
B

array([[1, 1, 2],
       [1, 1, 5],
       [6, 7, 8]])

In [26]:
# Creating a view of array. Note that it's not a copy of array
C = np.array([1, 1, 1, 1])
c_view = C[0:2]
print(c_view)
c_view[0] = 2
print(C)

[1 1]
[2 1 1 1]


In [27]:
# An array with 10 elements of size 2 will be:
r_i = np.random.rand(10, 2)
print(r_i)

[[0.83364319 0.30090436]
 [0.29373561 0.23152675]
 [0.73913821 0.73721429]
 [0.87001228 0.34251589]
 [0.17990193 0.34574293]
 [0.20438542 0.83009006]
 [0.96448012 0.70690055]
 [0.69179647 0.36687936]
 [0.44447851 0.18160577]
 [0.71281622 0.87858517]]


In [28]:
# getting x component of each coordinate
x_i = r_i[:, 0]
print(x_i)

[0.83364319 0.29373561 0.73913821 0.87001228 0.17990193 0.20438542
 0.96448012 0.69179647 0.44447851 0.71281622]


In [29]:
# getting all components of first row
y_i = r_i[0, :]
print(y_i)
# or
print(r_i[0])

[0.83364319 0.30090436]
[0.83364319 0.30090436]


### Fance indexing

In [30]:
# index an array using another Numpy array
d = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
idx = np.array([0, 2, 3])
d[idx]

array([9, 7, 6])

In [31]:
# fancy indexing on multiple dimensions
e = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
idx1 = np.array([0, 1])
idx2 = np.array([2, 2])
# e[select rows 0 and 1, select cols 2 and 2]
e[idx1, idx2]

array([2, 5])

In [32]:
# using normal lists
print(e[np.array([0, 1])])
# or
print(e[[0, 1]])

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [33]:
# using tuple
print(e[(0, 1)])
# or
print(e[0, 1])

1
1


In [34]:
# using multi-dimension index arrays
idx1 = [[0, 1], [3, 2]]
idx2 = [[0, 2], [1, 1]]
e[idx1, idx2]

array([[ 0,  5],
       [10,  7]])

In [35]:
# combining slicing and fancy indexing to swap x and y
r_i = np.random.rand(10, 2)
print(r_i)
r_i[:, [0, 1]] = r_i[:, [1, 0]]
print(r_i)

[[0.48303481 0.31904174]
 [0.71424486 0.55543377]
 [0.73155473 0.79732657]
 [0.29661636 0.06212525]
 [0.38651257 0.16837708]
 [0.98936878 0.99055018]
 [0.74196265 0.50096504]
 [0.96374717 0.99267999]
 [0.59281623 0.31551814]
 [0.4430549  0.00908099]]
[[0.31904174 0.48303481]
 [0.55543377 0.71424486]
 [0.79732657 0.73155473]
 [0.06212525 0.29661636]
 [0.16837708 0.38651257]
 [0.99055018 0.98936878]
 [0.50096504 0.74196265]
 [0.99267999 0.96374717]
 [0.31551814 0.59281623]
 [0.00908099 0.4430549 ]]


In [36]:
# using a bool type index array. every element corresponding to true will be extracted. this is called mask
f = np.array([0, 1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, False, False])
f[mask]

array([0, 2])

In [37]:
# getting more performance using np.take
r_i = np.random.rand(100, 2)
idx = np.arange(50)

In [38]:
%timeit r_i[idx]

2.36 µs ± 76.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [39]:
%timeit np.take(r_i, idx, axis=0)

2.84 µs ± 73.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
# Here np.take shows less performance than normal which is against the performance mentioned in the book.

In [41]:
# when index array is of boolean type we will use numpy.compress 
idx = np.ones(100, dtype='bool')

In [42]:
%timeit r_i[idx]

3.28 µs ± 86.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [43]:
%timeit np.compress(idx, r_i, axis=0)

3.05 µs ± 49.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [44]:
# np.compress is giving a slight speed improvement.